# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engram_contracts.rpc import engram_pb2 as engram__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engram_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextStub:
    """Internal RPC. Browsers never call these services.
    Complex records stay JSON so the Pydantic contracts remain the source of shape.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/engram.v1.Context/Check',
                request_serializer=engram__pb2.HealthRequest.SerializeToString,
                response_deserializer=engram__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamTurn = channel.unary_stream(
                '/engram.v1.Context/StreamTurn',
                request_serializer=engram__pb2.StreamTurnRequest.SerializeToString,
                response_deserializer=engram__pb2.StreamTurnEvent.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/engram.v1.Context/GetChat',
                request_serializer=engram__pb2.GetChatRequest.SerializeToString,
                response_deserializer=engram__pb2.GetChatResponse.FromString,
                _registered_method=True)
        self.ListRecent = channel.unary_unary(
                '/engram.v1.Context/ListRecent',
                request_serializer=engram__pb2.ListRecentRequest.SerializeToString,
                response_deserializer=engram__pb2.ListRecentResponse.FromString,
                _registered_method=True)
        self.EnsureGreeting = channel.unary_unary(
                '/engram.v1.Context/EnsureGreeting',
                request_serializer=engram__pb2.EnsureGreetingRequest.SerializeToString,
                response_deserializer=engram__pb2.EnsureGreetingResponse.FromString,
                _registered_method=True)
        self.DeleteByCharacter = channel.unary_unary(
                '/engram.v1.Context/DeleteByCharacter',
                request_serializer=engram__pb2.CharacterRef.SerializeToString,
                response_deserializer=engram__pb2.Ack.FromString,
                _registered_method=True)
        self.GetInspection = channel.unary_unary(
                '/engram.v1.Context/GetInspection',
                request_serializer=engram__pb2.GetInspectionRequest.SerializeToString,
                response_deserializer=engram__pb2.GetInspectionResponse.FromString,
                _registered_method=True)
        self.StampExtract = channel.unary_unary(
                '/engram.v1.Context/StampExtract',
                request_serializer=engram__pb2.StampExtractRequest.SerializeToString,
                response_deserializer=engram__pb2.Ack.FromString,
                _registered_method=True)


class ContextServicer:
    """Internal RPC. Browsers never call these services.
    Complex records stay JSON so the Pydantic contracts remain the source of shape.

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureGreeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInspection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StampExtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=engram__pb2.HealthRequest.FromString,
                    response_serializer=engram__pb2.HealthResponse.SerializeToString,
            ),
            'StreamTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTurn,
                    request_deserializer=engram__pb2.StreamTurnRequest.FromString,
                    response_serializer=engram__pb2.StreamTurnEvent.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=engram__pb2.GetChatRequest.FromString,
                    response_serializer=engram__pb2.GetChatResponse.SerializeToString,
            ),
            'ListRecent': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecent,
                    request_deserializer=engram__pb2.ListRecentRequest.FromString,
                    response_serializer=engram__pb2.ListRecentResponse.SerializeToString,
            ),
            'EnsureGreeting': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureGreeting,
                    request_deserializer=engram__pb2.EnsureGreetingRequest.FromString,
                    response_serializer=engram__pb2.EnsureGreetingResponse.SerializeToString,
            ),
            'DeleteByCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByCharacter,
                    request_deserializer=engram__pb2.CharacterRef.FromString,
                    response_serializer=engram__pb2.Ack.SerializeToString,
            ),
            'GetInspection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInspection,
                    request_deserializer=engram__pb2.GetInspectionRequest.FromString,
                    response_serializer=engram__pb2.GetInspectionResponse.SerializeToString,
            ),
            'StampExtract': grpc.unary_unary_rpc_method_handler(
                    servicer.StampExtract,
                    request_deserializer=engram__pb2.StampExtractRequest.FromString,
                    response_serializer=engram__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engram.v1.Context', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engram.v1.Context', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Context:
    """Internal RPC. Browsers never call these services.
    Complex records stay JSON so the Pydantic contracts remain the source of shape.

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/Check',
            engram__pb2.HealthRequest.SerializeToString,
            engram__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/engram.v1.Context/StreamTurn',
            engram__pb2.StreamTurnRequest.SerializeToString,
            engram__pb2.StreamTurnEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/GetChat',
            engram__pb2.GetChatRequest.SerializeToString,
            engram__pb2.GetChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/ListRecent',
            engram__pb2.ListRecentRequest.SerializeToString,
            engram__pb2.ListRecentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureGreeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/EnsureGreeting',
            engram__pb2.EnsureGreetingRequest.SerializeToString,
            engram__pb2.EnsureGreetingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/DeleteByCharacter',
            engram__pb2.CharacterRef.SerializeToString,
            engram__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInspection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/GetInspection',
            engram__pb2.GetInspectionRequest.SerializeToString,
            engram__pb2.GetInspectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StampExtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Context/StampExtract',
            engram__pb2.StampExtractRequest.SerializeToString,
            engram__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/engram.v1.Llm/Check',
                request_serializer=engram__pb2.HealthRequest.SerializeToString,
                response_deserializer=engram__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_stream(
                '/engram.v1.Llm/Complete',
                request_serializer=engram__pb2.CompleteRequest.SerializeToString,
                response_deserializer=engram__pb2.CompleteEvent.FromString,
                _registered_method=True)
        self.CompleteJson = channel.unary_unary(
                '/engram.v1.Llm/CompleteJson',
                request_serializer=engram__pb2.CompleteJsonRequest.SerializeToString,
                response_deserializer=engram__pb2.CompleteJsonResponse.FromString,
                _registered_method=True)


class LlmServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=engram__pb2.HealthRequest.FromString,
                    response_serializer=engram__pb2.HealthResponse.SerializeToString,
            ),
            'Complete': grpc.unary_stream_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=engram__pb2.CompleteRequest.FromString,
                    response_serializer=engram__pb2.CompleteEvent.SerializeToString,
            ),
            'CompleteJson': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJson,
                    request_deserializer=engram__pb2.CompleteJsonRequest.FromString,
                    response_serializer=engram__pb2.CompleteJsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engram.v1.Llm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engram.v1.Llm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Llm:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Llm/Check',
            engram__pb2.HealthRequest.SerializeToString,
            engram__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/engram.v1.Llm/Complete',
            engram__pb2.CompleteRequest.SerializeToString,
            engram__pb2.CompleteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Llm/CompleteJson',
            engram__pb2.CompleteJsonRequest.SerializeToString,
            engram__pb2.CompleteJsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/engram.v1.Memory/Check',
                request_serializer=engram__pb2.HealthRequest.SerializeToString,
                response_deserializer=engram__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/engram.v1.Memory/List',
                request_serializer=engram__pb2.ListMemoriesRequest.SerializeToString,
                response_deserializer=engram__pb2.JsonReply.FromString,
                _registered_method=True)
        self.Rank = channel.unary_unary(
                '/engram.v1.Memory/Rank',
                request_serializer=engram__pb2.RankRequest.SerializeToString,
                response_deserializer=engram__pb2.JsonReply.FromString,
                _registered_method=True)
        self.DiscardTurn = channel.unary_unary(
                '/engram.v1.Memory/DiscardTurn',
                request_serializer=engram__pb2.DiscardTurnRequest.SerializeToString,
                response_deserializer=engram__pb2.DiscardTurnResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/engram.v1.Memory/Update',
                request_serializer=engram__pb2.UpdateMemoryRequest.SerializeToString,
                response_deserializer=engram__pb2.JsonReply.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/engram.v1.Memory/Delete',
                request_serializer=engram__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=engram__pb2.Ack.FromString,
                _registered_method=True)
        self.DeleteByCharacter = channel.unary_unary(
                '/engram.v1.Memory/DeleteByCharacter',
                request_serializer=engram__pb2.CharacterRef.SerializeToString,
                response_deserializer=engram__pb2.Ack.FromString,
                _registered_method=True)


class MemoryServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscardTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=engram__pb2.HealthRequest.FromString,
                    response_serializer=engram__pb2.HealthResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=engram__pb2.ListMemoriesRequest.FromString,
                    response_serializer=engram__pb2.JsonReply.SerializeToString,
            ),
            'Rank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rank,
                    request_deserializer=engram__pb2.RankRequest.FromString,
                    response_serializer=engram__pb2.JsonReply.SerializeToString,
            ),
            'DiscardTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscardTurn,
                    request_deserializer=engram__pb2.DiscardTurnRequest.FromString,
                    response_serializer=engram__pb2.DiscardTurnResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=engram__pb2.UpdateMemoryRequest.FromString,
                    response_serializer=engram__pb2.JsonReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=engram__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=engram__pb2.Ack.SerializeToString,
            ),
            'DeleteByCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByCharacter,
                    request_deserializer=engram__pb2.CharacterRef.FromString,
                    response_serializer=engram__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engram.v1.Memory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engram.v1.Memory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Memory:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/Check',
            engram__pb2.HealthRequest.SerializeToString,
            engram__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/List',
            engram__pb2.ListMemoriesRequest.SerializeToString,
            engram__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/Rank',
            engram__pb2.RankRequest.SerializeToString,
            engram__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscardTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/DiscardTurn',
            engram__pb2.DiscardTurnRequest.SerializeToString,
            engram__pb2.DiscardTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/Update',
            engram__pb2.UpdateMemoryRequest.SerializeToString,
            engram__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/Delete',
            engram__pb2.DeleteMemoryRequest.SerializeToString,
            engram__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.Memory/DeleteByCharacter',
            engram__pb2.CharacterRef.SerializeToString,
            engram__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
